version : "3.8"
services:
  front:
    image: verretech_front
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=treafik_default"
        - "traefik.constraint-label=treafik_default"
        - "traefik.http.routers.verretech.rule=Host(`verre-tech.florianstock.fr`)"
        - "traefik.http.routers.verretech.entrypoints=websecure"
        - "traefik.http.services.verretech.loadbalancer.server.port=5000"
        - "entrypoints.web.http.redirections.entrypoint.permanent=true"
        - "traefik.http.routers.verretech.tls=true"
        - "traefik.http.routers.verretech.tls.certresolver=myresolver"
      replicas: 2
      placement:
        max_replicas_per_node: 1
    networks:
      - verretech_network
      - treafik_default
    ports:
      - 5000:5000
  traefik: 
        image: traefik:v2.4
        ports:
          - target: 80
            published: 80 
            protocol: tcp 
            mode: host 
        command: 
          - --providers.docker.swarmMode=true 
          - --providers.docker.exposedByDefault=false 
          - --providers.docker.network=proxy 
          - --entrypoints.web.address=:80 
          - --accesslog 
          - --log.level=debug 
        volumes: 
          - /var/run/docker.sock:/var/run/docker.sock:ro 
        networks: 
          - proxy 
        deploy: 
            mode: global 
            replicas: 1
            placement: 
                constraints: 
                  - node.role == manager 
  networks:
    verretech_network: 
      external:
        name: verretech_network
    proxy: 
      external: true