version : "3.8"
services:
  front:
    image: verretech_front
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.constraint-label=proxy"
        - "traefik.http.routers.verretech.rule=Host(`verre-tech.florianstock.fr`)"
        - "traefik.http.routers.verretech.entrypoints=websecure"
        - "traefik.http.services.verretech.loadbalancer.server.port=5000"
        - "entrypoints.web.http.redirections.entrypoint.permanent=true"
        - "traefik.http.routers.verretech.tls=true"
        - "traefik.http.routers.verretech.tls.certresolver=myresolver"
      replicas: 2
    networks:
      - verretech_network
      - proxy
    ports:
      - 5000:5000
networks:
    verretech_network: 
      external:
        name: verretech_network
    proxy: 
      external: true