version : "3.8"
services:
  front:
    image: verretech_front
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
    networks:
      - verretech_network
    ports:
      - 5000:5000
networks:
  verretech_network: 
      name: verretech_network