version : "3.8"
services:
  front:
    image: verretech_front
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=treafik_default"
        - "traefik.constraint-label=treafik_default"
        - "traefik.http.routers.wiki-bc.rule=Host(`verre-tech.florianstock.fr`)"
        - "traefik.http.routers.wiki-bc.entrypoints=websecure"
        - "traefik.http.services.wiki-bc.loadbalancer.server.port=5000"
        - "entrypoints.web.http.redirections.entrypoint.permanent=true"
        - "traefik.http.routers.wiki-bc.tls=true"
        - "traefik.http.routers.wiki-bc.tls.certresolver=myresolver"
      replicas: 2
      placement:
        max_replicas_per_node: 1
    networks:
      - verretech_network
    ports:
      - 5000:5000
networks:
  verretech_network: 
      name: verretech_network